export function createSound(){
 let context,master,ambientSource,ambientGain,musicSource,volume=.35,started=false,paused=true;
 const buffers=new Map(),decoded=new Set();
 async function load(name){if(buffers.has(name))return buffers.get(name);const promise=fetch(`survival/assets/${name}.ogg`).then(r=>{if(!r.ok)throw Error('Audio unavailable');return r.arrayBuffer();}).then(b=>context.decodeAudioData(b)).then(b=>{decoded.add(name);return b;});buffers.set(name,promise);return promise;}
 async function start(){if(started){await context?.resume();return;}started=true;try{context=new AudioContext();master=context.createGain();master.gain.value=volume;master.connect(context.destination);await context.resume();const buffer=await load('mountain');ambientSource=context.createBufferSource();ambientGain=context.createGain();ambientGain.gain.value=.13;ambientSource.buffer=buffer;ambientSource.loop=true;ambientSource.connect(ambientGain);ambientGain.connect(master);ambientSource.start();}catch{/* Audio loading must not block the game. */}}
 async function effect(name,gain=.45,pan=0){try{if(!context)return;const buffer=await load(name),source=context.createBufferSource(),g=context.createGain(),p=context.createStereoPanner();source.buffer=buffer;g.gain.value=gain;p.pan.value=pan;source.connect(g);g.connect(p);p.connect(master);source.start();source.onended=()=>{source.disconnect();g.disconnect();p.disconnect();};}catch{/* Optional audio fails quietly. */}}
 async function music(){try{if(!context||musicSource)return;const buffer=await load('ink-theme');musicSource=context.createBufferSource();const g=context.createGain();g.gain.value=.3;musicSource.buffer=buffer;musicSource.connect(g);g.connect(master);musicSource.start();musicSource.onended=()=>{musicSource=null;g.disconnect();};}catch{/* The recovered record stays available without audio. */}}
 return {start,effect,music,setVolume(v){volume=v;if(master)master.gain.setTargetAtTime(v,context.currentTime,.15);},setPaused(v){paused=v;if(context){if(v)context.suspend();else context.resume();}},get status(){return {started,paused,context:context?.state||'not-started',decoded:decoded.size,musicPlaying:!!musicSource,volume};}};
}
